spring:
  application:
    name: crud-sample

  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin@123
    url: jdbc:postgresql://localhost:5432/crud_db

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  mvc:
    problemdetails:
      enabled: true

application:
  # Jwt Configuration
  jwt:
    config:
      encryption-key: 5heUCJxsTsaYyTE6+XB+tnpvdZkttNv5PBWHe9v9q73kGjDa2+UI2YQMWPj1Fpec
      # Expiration in milliseconds
      token-expiration: 600000 # 10 minutes

logging:
  level:
    com.example.crud_sample: INFO
